import argparse
import pandas as pd
from helper import join_dataframe
import os
"""
Script: join_rmse_dataframes.py

Description:
    This script merges multiple CSV files containing RMSE distribution results
    (e.g., generated by `main_generate_rmse_dist_param.py`) into a single consolidated CSV file.

    It loads the input CSVs, joins them using the `join_dataframe` function from the `helper` module,
    and writes the merged result to the specified output location.

Usage:
    python join_rmse_dataframes.py \
        --dataframes file1.csv file2.csv ... \
        --result_dir /path/to/output/ \
        --result_name joined.csv

Arguments:
    --dataframes    [required] One or more paths to CSV files to merge.
    --result_dir    [required] Output directory where the merged file will be saved.
    --result_name   [required] Filename for the output CSV file.

Output:
    A single CSV file containing the joined data from all input files, saved to:
    {result_dir}/{result_name}
"""

parser = argparse.ArgumentParser()
parser.add_argument("--dataframes", required=True, default=None, type=str, nargs='+',help="Paths to csv files with rmse distribution generated by \"main_generate_rmse_dist_param.py\".")
parser.add_argument("--result_dir",required=True ,default=None, type=str, help="Directory where output results will be stored.")
parser.add_argument("--result_name",required=True, default=None, type=str, help="Name of the resulting output file (e.g., joined.csv).")


def main(args):

    dataframes = [pd.read_csv(fp) for fp in args.dataframes]

    result_df = join_dataframe(*dataframes)

    os.makedirs(args.result_dir, exist_ok=True)
    output_path = os.path.join(args.result_dir, args.result_name)
    result_df.to_csv(output_path, index=False)

if __name__ == '__main__':
    args = parser.parse_args()
    main(args)