import argparse
import pandas as pd
from helper import join_dataframe
import os
parser = argparse.ArgumentParser()
parser.add_argument("--dataframes", required=True, type=str, nargs='+',help="Paths to csv files with rmse distribution generated by \"main_generate_rmse_dist_param.py\".")
parser.add_argument("--result_dir", default=None, type=str, help="Directory where output results will be stored.")
parser.add_argument("--result_name", default=None, type=str, help="Name of the resulting output file (e.g., joined.csv).")


def main(args):

    dataframes = [pd.read_csv(fp) for fp in args.dataframes]

    result_df = join_dataframe(*dataframes)

    os.makedirs(args.result_dir, exist_ok=True)
    output_path = os.path.join(args.result_dir, args.result_name)
    result_df.to_csv(output_path, index=False)

if __name__ == '__main__':
    args = parser.parse_args()
    main(args)