"""
Author: Radoslav Jochman
"""
import plotting
import argparse
import helper
import pandas as pd
parser = argparse.ArgumentParser()
parser.add_argument("--data_location", default=None, type=str, help="Path to a csv file with rmse distribution generated by \"main_generate_rmse_dist_param.py\".")
parser.add_argument("--result_dir", default=None, type=str, help="Directory where output results will be stored.")
parser.add_argument("--result_name", default=None, type=str, help="Name of the graph.")

def main(args: argparse.Namespace):
    rmse_dist =pd.read_csv(args.data_location)
    p = plotting.ggplot_average_heatmap_param(rmse_dist)
    p.save(filename=f"{args.result_dir}/{args.result_name}", width=8, height=8, dpi=300)
if __name__ == '__main__':
    args = parser.parse_args()
    main(args)